### ISSUE TITLE
[scripts] Crash of add_population

### ISSUE THREAD

**Issue by albertvillanova** [albertvillanova/WikidataBot#10]
```
Traceback (most recent call last):
  File "./scripts/add_population.py", line 441, in <module>
    params=params
  File "./scripts/add_population.py", line 281, in main
    print(i + 1, administrative_division.labels['fr'])
KeyError: 'fr'
CRITICAL: Exiting due to uncaught exception <class 'KeyError'>

```

**Comment by albertvillanova** [comment]
Due to Q49004369 (wrong item, merged with Q701110).
