### ISSUE TITLE
[scripts] Crash of add_population

### ISSUE THREAD

**Issue by albertvillanova** [albertvillanova/WikidataBot#16]
```
2020-01-15 06:54:15,276 [    INFO] Item: Ausseing (Q766675) with INSEE code 31030
Traceback (most recent call last):
  File "./scripts/add_population.py", line 526, in <module>
    logger.info(f"Summary: {summary}")
  File "./scripts/add_population.py", line 371, in main
    # Create population statement
  File "./scripts/add_population.py", line 273, in check_duplicates
    # TODO: warn if new statement has different amount but the same year (see Paris)
  File "c:\users\myusername\projects\wikidata\pywikibot\pywikibot\page.py", line 3914, in __getattribute__
    return super(WikibasePage, self).__getattribute__(name)
AttributeError: 'ItemPage' object has no attribute 'year'
CRITICAL: Exiting due to uncaught exception <class 'AttributeError'>
```

**Comment by albertvillanova** [comment]
Function check_duplicates assumes all qualifiers of the population claim are dates:
```
if statement_qualifier_claim.getTarget().year == new_statement_qualifier_claim.getTarget().year:
```
Note that now there might be also the qualifier *determination method* (P459), besides the usual *point in time* (P585).
