### ISSUE TITLE
[scripts] Logging error because of encoding

### ISSUE THREAD

**Issue by albertvillanova** [albertvillanova/WikidataBot#33]
```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\AVI14827\AppData\Local\Continuum\anaconda3\envs\wikidata\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\AVI14827\AppData\Local\Continuum\anaconda3\envs\wikidata\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 531-533: character maps to <undefined>
```

**Comment by albertvillanova** [comment]
If FileHandler encoding is not specified, it assumes the system default encoding (for Windows: cp1252).
